name: Rust-Hypervisor-Firmware's Docker image update

on:
  push:
    branches: main
    paths: resources/Dockerfile
  pull_request:
    paths: resources/Dockerfile

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          file: ./resources/Dockerfile
          platforms: linux/amd64
          push: true
          tags: rusthypervisorfirmware/dev:latest

      - name: Build only
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          file: ./resources/Dockerfile
          platforms: linux/amd64
          tags: rusthypervisorfirmware/dev:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
