name: Rust-Hypervisor-Firmware's Docker image update

on:
  push:
    branches: main
    paths:
      - resources/Dockerfile
      - rust-toolchain.toml
  pull_request:
    paths:
      - resources/Dockerfile
      - rust-toolchain.toml
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get active Rust toolchain
        id: get-toolchain
        run: echo "toolchain=`rustup show active-toolchain | cut -d ' ' -f1`" >> $GITHUB_ENV

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true

      - name: Build
        uses: docker/build-push-action@v3
        with:
          file: ./resources/Dockerfile
          build-args: |
            RUST_TOOLCHAIN=${{ env.toolchain }}
          platforms: |
            linux/arm64
            linux/amd64
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
