name: Rust-Hypervisor-Firmware's Docker image update

on:
  push:
    branches: main
    paths:
      - resources/Dockerfile
      - rust-toolchain.toml
  pull_request:
    paths:
      - resources/Dockerfile
      - rust-toolchain.toml

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Get active Rust toolchain
        id: get-toolchain
        run: echo "toolchain=`rustup show active-toolchain | cut -d ' ' -f1`" >> $GITHUB_ENV

      - name: Login to DockerHub
        if: ${{ github.repository == 'cloud-hypervisor/rust-hypervisor-firmware' && github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          file: ./resources/Dockerfile
          build-args: |
            RUST_TOOLCHAIN=${{ env.toolchain }}
          platforms: linux/amd64
          push: ${{ github.repository == 'cloud-hypervisor/rust-hypervisor-firmware' && github.event_name == 'push' }}
          tags: rusthypervisorfirmware/dev:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
