name: Rust Hypervisor Firmware Tests
on: [pull_request, merge_group]

jobs:
  build:
    name: Tests
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            coreboot-tests: true
          - runner: focal-arm64
            coreboot-tests: false
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run unit tests
        run: scripts/dev_cli.sh tests --unit
      - name: Run integration tests
        run: scripts/dev_cli.sh tests --integration
      - if: ${{ matrix.coreboot-tests }}
        name: Run coreboot integration tests
        run: scripts/dev_cli.sh tests --integration-coreboot
